### ISSUE TITLE
Backend = Instanced causing stack overflow when joining server

### ISSUE THREAD

**Issue by nanakisan** [Engine-Room/Flywheel#168]
### Describe the Bug

Joining server causes stack overflow. No crashlogs present. This is a JVM crash. Attached is my dump file
[hs_err_pid13744-1.log](https://github.com/Jozufozu/Flywheel/files/10340368/hs_err_pid13744-1.log)

Solution: Turning Instanced to Off

I do not have a MC crash that could provide pointers on the matter.

### Reproduction Steps

Install modpack
Try to play on server
Client crashes with JVM error

### Expected Result

Being able to log in

### Operating System

Windows 10

### What is your GPU?

ASRock Phantom Gaming D RX 570

### Mod Version

0.6.8

### Minecraft Version

1.18.2

### Loader Version

Forge 40.2.0

### Other Mods

AI-Improvements-1.18.2-0.5.2.jar
appleskin-forge-mc1.18.2-2.4.1.jar
Aquaculture-1.18.2-2.3.10.jar
arcaneadditions-1.5.0.jar
architectury-4.10.88-forge.jar
AttributeFix-Forge-1.18.2-14.0.2.jar
bmorph-1.18.2-2.0.1.jar
Bookshelf-Forge-1.18.2-13.2.50.jar
cfm-7.0.0-pre29-1.18.2.jar
champions-forge-1.18.2-2.1.6.2.jar
chipped-2.0.0-forge.jar
cloth-config-6.4.90-forge.jar
Clumps-forge-1.18.2-8.0.0+17.jar
CodeChickenLib-1.18.2-4.1.2.475-universal.jar
corpse-1.18.2-1.0.1.jar
CosmeticArmorReworked-1.18.2-v2a.jar
create-1.18.2-0.5.0.g.jar
create-confectionery1.18.2_v1.0.8.jar
create-stuff-additions1.18.2_v2.0.2a.jar
createdeco-1.2.12-1.18.2.jar
CTM-1.18.2-1.1.5+5.jar
curios-forge-1.18.2-5.0.7.1.jar
dragonfight-1.18.2-2.2.jar
dusk-1.18.2-2.1.jar
EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar
EnderStorage-1.18.2-2.9.0.182-universal.jar
FarmersDelight-1.18.2-1.2.0.jar
FarmersRespite-1.18.2-1.3.0.jar
FastLeafDecay-28.jar
flywheel-forge-1.18.2-0.6.8.jar
ftb-chunks-forge-1802.3.12-build.217.jar
ftb-library-forge-1802.3.9-build.167.jar
ftb-teams-forge-1802.2.9-build.88.jar
fxbuildup-0.0.2.jar
geckolib-forge-1.18-3.0.57.jar
grappling_hook_mod-1.18.2-v13.jar
hexerei-0.2.2.jar
honeyexpansion-1.1.1.jar
IKnowWhatImDoing-5.0.0-forge.jar
jei-1.18.2-9.7.1.255.jar
kotlinforforge-3.8.0-obf.jar
libIPN-forge-1.18.2-2.0.1.jar
lootr-1.18.2-0.2.23.60.jar
mcw-bridges-2.0.6-mc1.18.2forge.jar
mna-1.7.2.10.jar
modonomicon-1.18.2-1.23.2.jar
MouseTweaks-forge-mc1.18-2.21.jar
mystic_alchemy-0.0.9.jar
occultism-1.18.2-1.64.0.jar
oculus-1.4.3.jar
Patchouli-1.18.2-71.1.jar
Placebo-1.18.2-6.6.6.jar
rubidium-0.5.4.jar
selene-1.18.2-1.17.9.jar
simplemagnets-1.1.8-forge-mc1.18.jar
SmartBrainLib-forge-1.18.2-1.7.4.jar
SoL-Carrot-1.18.1-1.12.0.jar
spark-1.9.11-forge.jar
StorageDrawers-1.18.2-10.2.1.jar
supermartijn642configlib-1.1.6-forge-mc1.18.jar
supermartijn642corelib-1.0.19-forge-mc1.18.jar
supplementaries-1.18.2-1.5.14.jar
theoneprobe-1.18-5.1.2.jar
theurgy-1.18.2-1.1.1.jar
ToastControl-1.18.2-6.0.3.jar
ToolBelt-1.18.2-1.18.9.jar
XaerosWorldMap_1.28.7_Forge_1.18.2.jar
Xaeros_Minimap_22.17.0_Forge_1.18.2.jar

### Additional Context

Hopefully I have given all the information I can. I have no other clues as to why this happened.

**Comment by MoonStalk** [comment]
Problem also occurs on 1.19.2 with AMD GPU

[hs_err_pid5388.log](https://github.com/Jozufozu/Flywheel/files/10391526/hs_err_pid5388.log)

**Comment by Marfjeh** [comment]
I was able to reproduce this issue on 2 machines. out of 3. All of them has a AMD GPU.
2 other machines i also access to have a Nvidia graphics card, which worked without issue.

I do get the same JVM crash error as stated in the author's provided log file.
But it also sometimes crashes with no crash in the JVM but only exits with a exit code: `-1073741571`
I also tried to use different JVM verisons 17, 18 and JVM vendors like Oracle's JDK, OpenJDK from Microsoft, Azul, adopt. All the same issue.
Also setting the backend to "Batching" also seems to fix the issue for now.

I strongly suspect this is a AMD Graphics driver issue,  because i was unable to reproduce the issue at first on System 2, it was still using the drivers provided by microsoft, however it had alot of graphics artifacting like Chests didnt render correctly only the top rendered and the bottom part was invisble, on the floor there was a black square with alot of z fighting. even though in vanilla it worked fine. until flywheel was installed.
I also ran the mod on a SteamDeck running SteamOS (Beta) 3.4 and it worked fine. no crashes. no artifacting.

Flywheel version: `1.18.2-0.6.8`

### System 1 spec:
```
CPU: AMD Ryzen 5 5600X.
GPU: AMD Radeon 6700 XT (Driver version: Adrenalin 22.11.2)
RAM: 32GB.
OS: Windows 10 22H2
Ram allocated to the game: 6G. no other jvm arguments then what mojang uses.
Launcher: Prism Launcher
```

### System 2 spec:
```
CPU: AMD Ryzen 9 7950X
GPU: Radeon Graphics from CPU (Driver version: Adrenalin 22.11.1 Optional (WHQL))
RAM: 64GB
OS: Windows 10 Enterprise LTSC 21H2
Ram allocated to the game: 6G. no other jvm arguments then what mojang uses.
Launcher: Prism Launcher
```
[hs_err_pid11240.log](https://github.com/Jozufozu/Flywheel/files/10399708/hs_err_pid11240.log)
This log file has been generated on system 2.

Mod list: [modlist.txt](https://github.com/Jozufozu/Flywheel/files/10399836/modlist.txt)

**Comment by PepperCode1** [comment]
Duplicate of #164.
