### ISSUE TITLE
Flywheel ghost version

### ISSUE THREAD

**Issue by IsaacAMurray** [Engine-Room/Flywheel#197]
### Describe the Bug

I am playing a custom mod pack I am building on the curse forge client. I will try to start the latest version of all my mods and I keep getting an error from forge saying that some files require another version of flywheel that does not exist in the files menu. Images attached.

### Reproduction Steps

1. Install the create mod, flywheel and the mods listed in the screenshot
2. run the mod pack

### Expected Result

The game was expected to boot up normally.

### Screenshots and Videos

![CurseForge 7_29_2023 2_28_12 AM](https://github.com/Jozufozu/Flywheel/assets/48367019/48ff568f-9309-41d9-8454-91cf5d0ff21a)
![CurseForge 7_29_2023 2_31_09 AM](https://github.com/Jozufozu/Flywheel/assets/48367019/dd23c415-e47a-4ebe-82de-e88fc8d48701)
![Minecraft_ 1 18 2 7_29_2023 2_32_21 AM](https://github.com/Jozufozu/Flywheel/assets/48367019/027f9b10-7acd-4778-bd46-19cf897c3d5a)
![Flywheel - Minecraft Mods - CurseForge — Mozilla Firefox 7_29_2023 3_24_09 AM](https://github.com/Jozufozu/Flywheel/assets/48367019/bda124fb-ce83-44e6-8b40-f3ee63bb0c32)

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3060

### Mod Version

0.6.8.a

### Minecraft Version

1.18.2

### Loader Version

Forge 40.2.10

### Other Mods

Create
Steam Powered
Compressed Creativity

### Additional Context

I checked the curse forge site and the curse forge client and found no versions of Flywheel higher than 0.6.8.a for 1.18.2

**Comment by Lana-chan** [comment]
until the version is properly uploaded to curseforge and modrinth you can get 0.6.9 from their maven: https://maven.tterrag.com/com/jozufozu/flywheel/flywheel-forge-1.18.2/0.6.9-101/

**Comment by PepperCode1** [comment]
Flywheel 0.6.9 will not be uploaded to CurseForge and Modrinth. It is included with Create 0.5.1.c/d and should not be installed separately.

**Comment by Lana-chan** [comment]
then it turns out my issue is that i had an older version of create which did *not* have flywheel built-in. in trying to update my modpack, i ran into the same issue where flywheel gets stuck in 0.6.8a and create 0.5.1 flags the issue. the correct procedure in that case then is not to update the discrete flywheel jar but to remove it altogether

since i did not look at the [curseforge page for create](https://www.curseforge.com/minecraft/mc-mods/create) to download it but rather just used my launcher's update feature, i was sent on a wild goose chase that led me here. hopefully others will find this useful now
