### ISSUE TITLE
render issue on create's tile entities

### ISSUE THREAD

**Issue by rakostep** [Engine-Room/Flywheel#3]
Hi there,

As what the subject title says, I'm not really seeing it as an issue since this mod is still under development. However I'd like to report about this in advanced. I can't put out some logs or some recorded stuff since it doesn't crash the game, it only fails to render Create's moving objects and such, but I can confirm it was this mod preventing it to render since when I removed it, the objects are visible.

So far though, the mod actually helped the lag issue I expereince when playing a single player modded minecraft, I really like the work.

**Comment by Jozufozu** [comment]
Flywheel was initially created inside Create as a more performant rendering engine. Create 0.3.1c will break with this mod installed because it still has Flywheel bundled inside of it. I'm glad you like the work, but Flywheel is not actually a performance mod, and does nothing on its own, so the performance gains you're experiencing are likely because Create isn't rendering anything.

**Comment by rakostep** [comment]
Ohhh I see, that explains a lot. Thank you for the response.
