### ISSUE TITLE
Game Crashes When looking in a specific Direction, soft locks effected world in a crash cycle.

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [Engine-Room/Flywheel#90]
(Forge 1.18.1)
This has happened twice around 5 minutes into a new survival world. I believe this may be a rendering issue cause if I manage to turn away within the 3-5 seconds I have before the game crashes, said crash doesn't occur unless I turn back around.

[crash-2022-01-04_13.03.28-client.txt](https://github.com/Jozufozu/Flywheel/files/7809564/crash-2022-01-04_13.03.28-client.txt)

The Crash Report has "Flywheel" in it, so I assume it's a bug with this mod. Could be a compatibility issue but I'm not a coder.

**Comment by Jozufozu** [comment]
This doesn't look like an issue caused by Flywheel. It seems like it's caused by the item you're holding.

Either way, does using the latest update to [Create](https://www.curseforge.com/minecraft/mc-mods/create/files/3600402) and [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3600401) fix it?

**Comment by AlexTheSuprWolf** [comment]
I completely forgot I made this bug report. Apologies, A different mod in my pack updated around 2 days later after I made this report, and the issue went away entirely.

Your free to close the issue. sorry for wasting your time.

**Comment by Jozufozu** [comment]
No worries! I'm glad it's resolved!
